### ISSUE TITLE
Act_8-Reporte de entrevista

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-5#1]
Act_8-Reporte de entrevista
equipo: Daisy Gonzalez Lita, Maribel Santiago Bautista, Ana Kimberly Hernández Pérez, Ariadna Monserrat López Aparicio.

[Reporte-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-5/files/9934273/Reporte-1.pdf)

**Comment by ErikCuevas03** [comment]
El reporte esta bien estructurado, incluye a su vez evidencias de la actividad.

Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
